# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  orderdelivery-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: orderdelivery-mysql
    volumes:
      - orderdelivery-mysql-data:/var/lib/mysql
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=order_delivery
      - MYSQL_DATABASE=order_delivery_db
      - MYSQL_USER=order_delivery
      - MYSQL_PASSWORD=order_delivery

  # PHP (with nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: order-delivery-backend-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql